Replace 'imgur' with 'fiware'
apinf/apinf-accounts-fiware pull request #7
Opened 2017-08-16 01:43 UTC by Vellames

Closes #1 

**WIP**

2017-08-16 02:00 UTC, Vellames commented
@mauriciovieira ready for review

2017-08-16 18:13 UTC, mauriciovieira requested changes
Please fix these points

2017-08-16 18:13 UTC, mauriciovieira commented on accounts-fiware_login_button.css
>      background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABAklEQVQ4jZ2RMU7DMBSGPwcnjauEuEYgKKgjI+IETJyhC+foSE/SBU7BJRALE2qZw4hgSEliMxVV1Ena/pOH933P7z0xebp9sM5eskd
@Vellames replace this image. or remove it. it's imgur image.

2017-08-16 18:13 UTC, mauriciovieira commented on package.js
> +  summary: 'OAuth2 for Fiware',
Should mention _FIWARE IdM_ here

2017-08-18 01:27 UTC, Vellames commented on package.js
> +  summary: 'OAuth2 for Fiware',
@mauriciovieira i need the fiware logo to put in package, where i can find a nice image of fiware?

2017-08-18 01:27 UTC, Vellames commented on accounts-fiware_login_button.css
>      background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABAklEQVQ4jZ2RMU7DMBSGPwcnjauEuEYgKKgjI+IETJyhC+foSE/SBU7BJRALE2qZw4hgSEliMxVV1Ena/pOH933P7z0xebp9sM5eskd
@mauriciovieira i need the fiware logo to put in package, where i can find a nice image of fiware?

2017-08-18 02:33 UTC, Vellames commented
@mauriciovieira or @midyan plase review the changes

2017-08-23 20:50 UTC, mauriciovieira approved these changes
LGTM

2017-08-23 20:50 UTC, merged